### ISSUE TITLE
Using same parent section in two separate files

### ISSUE THREAD

**Issue by Kamilius** [straker/livingcss#29]
I'm having a section Notifications and Form elements in my styleguide, with two subsections "alerts" and "form controls".  Both are split into two separate files. In order of appearance, `@section 1. Notifications and Form elements` is defined inside `form controls` file. Is there any way of using `@sectionof 1. Notifications and Form elements` inside "alerts" file? Currently I'm getting `ReferenceError: section '1. Notifications and Form elements' is not defined` error.

**Comment by straker** [comment]
Yes it is possible, and my guess is that it's just a race condition in how your code is getting parsed. If the alerts file is parsed first and tries to use a section that hasn't been defined yet (because the form controls file creates the definition), then what you'll need to do is specify the order of parsing in your glob selector of `livingcss`.

```
livingcss([
  `${dirName}/app/src/_common/styles/**/alert.scss`,
  `${dirName}/app/src/_common/styles/**/formControls.scss`,   
  `${dirName}/app/src/_common/styles/**/*.scss`
], `${dirName}/styleguide`, options);
```

If the ordering of the sections is then different, you can use the [sortOrder option](https://github.com/straker/livingcss#options) to fix it.

**Comment by straker** [comment]
Here is the entire livingcss call I make to parse the [FamilySearch styleguide](https://familysearch.org/reference/styleguide/) css (using the gulp plugin). It has some inter dependencies of definitions.

```
return gulp.src([
    'node_modules/fs-styles/assets/css/helpers/*.styl',
    'node_modules/fs-styles/assets/css/elements/*.styl',
    'node_modules/fs-styles/assets/css/modules/*.styl'
  ])
  .pipe(livingcss('views', {
    template: 'handlebars/template.hbs',
    preprocess: function(context, template, Handlebars) {
      findLoneSubsections(context.sections);

      return livingcss.utils.readFileGlobs('handlebars/partials/*.hbs', function(data, file) {
        Handlebars.registerPartial(path.basename(file, path.extname(file)), data);
      });
    },
    sortOrder: [
      {index: ['colors', 'break points', 'typography', 'lists', 'forms', 'buttons', 'icons', 'tooltips', 'badges', 'alerts', 'cards', 'subnav', 'modals']}
      ],
    tags: {
      colordef: function() {
        this.block.name = this.tag.description;
        this.block.description = this.comment.description;
        this.block.id = livingcss.utils.getId(this.block.name);
      },
      color: function() {
        this.block[this.tag.type] = this.tag.description;
      },
      colorof: function() {
        var section = this.sections[this.tag.description];

        if (section) {
          section.colors = section.colors || [];
          section.colors.push(this.block);
        }
      },
      icondef: function() {
        this.block.name = this.tag.description;
        this.block.description = this.comment.description;
        this.block.id = livingcss.utils.getId(this.block.name);
      },
      iconof: function() {
        var section = this.sections[this.tag.description];

        if (section) {
          section.icons = section.icons || [];
          section.icons.push(this.block);
        }
      }
    }
  }))
  .pipe(gulp.dest('views'));
});
```

**Comment by straker** [comment]
Sorry, wrong button click...

**Comment by Kamilius** [comment]
After using this method (first - file which declares parent section, then which uses it, and then specifying the rest of stylesheets), got an error:
`SyntaxError: section '1.1 Notifications' has already been declared within the section '1. Notifications and Form elements'`

Looks like it's parsing specified files, and then tries to parse'em again but within `**/*.scss` glob.

**Comment by straker** [comment]
So this is how I'm doing it for the familysearch styleguide (I'm using colors here with a custom tag function, but the concept is the same as @section and @sectionof):

https://github.com/fs-webdev/fs-styles/blob/master/assets/css/helpers/_variables.styl#L192-L200

```css
/**
 * Logo Colors
 *
 * ##### Acceptable Use
 *
 * The full 3-color logo is the primary logo and should be used in all instances when
 * possible.
 *
 * There may be some instances where a single color logo is appropriate, such as using the
 * FamilySearch logo on photography, apparel, spiffs, etc.
 *
 * ##### Avoid
 *
 * Do not use any other colors for the logo.
 *
 * @section
 * @sectionof Colors
 */

/**
 * Full Color Logo
 * @section
 * @sectionof Colors.Logo Colors
 */

 /**
 * Single Color Logos
 * @section
 * @sectionof Colors.Logo Colors
 */

/**
 * @colordef Green Primary
 * @color {hex} #87b940
 * @color {rgb} 135,185,64
 * @color {cmyk} 53,7,100,0
 * @colorof Colors.Logo Colors.Full Color Logo
 * @colorof Colors.Logo Colors.Single Color Logos
 */
$color-green-primary = #87b940;
```

So you should declare your sections first, so that they are there when you want to do @sectionof, then use @sectionof to link the section to both sections. Then use the file ordering and section ordering to get it organized.

Since these are two different files that want to share a section, it might be a little awkward to declare the section for another file in a different file. I'm not sure if there's a good way to solve that one.

**Comment by Kamilius** [comment]
In my case, only specifying an exclude glob helped:
```js
livingcss([
  `${dirName}/app/src/_common/styles/**/alert.scss`,
  `${dirName}/app/src/_common/styles/**/formControls.scss`,   
  `${dirName}/app/src/_common/styles/**/!(alert|formControls).scss`
], `${dirName}/styleguide`, options);
```

This ensures `alert.scss` and `formControls.scss` are being parsed only once.

**Comment by Kamilius** [comment]
I'll be closing this, as a workaround found.
