### ISSUE TITLE
Valid SCSS code blocks are parsed improperly

### ISSUE THREAD

**Issue by sidraval** [straker/livingcss#35]
Hello again,

I'm using the SCSS syntax highlighting from prism, and the following code block causes livingcss to choke:

```
@code {scss}
.example {
  @extend %placeholder-selector;
}
```

My guess is that the `@extend` is getting registered as a tag by the parser. I'm not sure exactly how to resolve this, since there are not "closing" tags. Perhaps a list of exclusions, or a way to escape tags?

Valid SCSS includes `@include`, `@extend`, `@mixin`, etc.

Let me know if I can provide any more info 😄

**Comment by straker** [comment]
You are correct that the parser is parsing the `@extend` as a tag. There's not really anything I can do to fix it. I'm too tried to come up with a way to break the parser, but I'll look into it tomorrow.

The parser parses a line for tags using this regex: `/^\s*@(\w+)/)`. So any [whitespace characters](https://www.w3schools.com/jsref/jsref_regexp_whitespace.asp) followed by the `@` symbol and text. If we can come up with a way that breaks the parser but doesn't break copy-paste from the code block into the editor, that'd be the way to do it.

Otherwise, the only way I can think of right now is to put the `@extend` on the same line as the selector.

```
@code {scss}
.example { @extend %placeholder-selector; }
```

**Comment by straker** [comment]
Alright, I found a way to get this to work around the parser. The solution is to use the HTML entity encoding for the @ symbol `$#64;`.

```
@code {scss}
.example {
  $#64;extend %placeholder-selector;
}
```
