### ISSUE TITLE
User Contributed templates

### ISSUE THREAD

**Issue by sprynm** [straker/livingcss#55]
As discussed, might be fun to open up a space where people can post their templates, partials, helpers,  or custom tags etc.

**Comment by sprynm** [comment]
Any more thoughts on this?

**Comment by straker** [comment]
Sorry, forgot about this. Thanks for the reminder. I created the first page of the wiki. Since only collaborators can edit it I think the best flow would be to create an issue with your desired content to be added to the wiki and then i can move it into it.

I added a template to follow to hopefully keep it somewhat organized.

https://github.com/straker/livingcss/wiki/User-Generated-Content

**Comment by straker** [comment]
Closing as the structure has been set up
